### ISSUE TITLE
Language Codes as readable Constants

### ISSUE THREAD

**Issue by Bavragor** [MenaraSolutions/geographer#1]
What do you think about that ?

**Comment by dusterio** [comment]
Could you elaborate please? Where would you expect to see/keep the constants?

**Comment by Bavragor** [comment]
I guess i would see the constants in the Earth class.
Something like:
```php
const LANGUAGE_GERMAN = 'de';

Therefore you could use: $thailand->getStates()->setLanguage(Earth::LANGUAGE_GERMAN)
```

**Comment by dusterio** [comment]
Oh I see.
I already embedded national language codes into Country class, so $country->getLanguage() returns country's top language (if there are multiple - first one is used).

Therefore, you can achieve the same using:
$thailand->getStates()->setLanguage($thailand->getLanguage());

**Comment by dusterio** [comment]
And in the future, I guess I could also add a convenience method like ->useLocalLanguage() that does the same behind the scenes.

**Comment by dusterio** [comment]
Added the constants, see updated README
