### ISSUE TITLE
Lookup state by iso code?

### ISSUE THREAD

**Issue by kwilliams** [MenaraSolutions/geographer#2]
I'm having trouble finding a way to lookup a state by iso code, is this possible?

**Comment by kwilliams** [comment]
After poking through the matching function it looks like in order to do this we need to overload the toArray method of the State class, can I submit a pull request?

**Comment by dusterio** [comment]
Hi!

Have you tried $states->findOne(['isoCode' => $code])? Or directly from a country: $country->getStates()->findOne(...)

**Comment by kwilliams** [comment]
Yeah, the problem I'm running into is that the toArray method needs to be overridden with the getters for each Member.

`
>>> Geographer::findOne(['code' => 'US'])->findOne(['isoCode' => 'TX']);
=> false
`

The match method casts each object to an array before searching for key value pairs, which ends up limiting the search parameters \MenaraSolutions\Geographer\Divisible@toArray.

**Comment by kwilliams** [comment]
I see that this has been fixed in master, can we get a release for Composer purposes?

**Comment by dusterio** [comment]
Sure, it's done. I didn't actually expect anybody to download this package before July ;-) I'm in the middle of preparing the first public release and a blog post with documentation
