### ISSUE TITLE
Fails to load data if project is in a folder called "code"

### ISSUE THREAD

**Issue by AJenbo** [MenaraSolutions/geographer#25]
https://github.com/MenaraSolutions/geographer/blob/1f15dde4be9b5eb0222871e159ffc99621b26942/src/Repositories/File.php#L87

It took me quite some time to figure out why the libery was failing to load any data on some systems. Please restrict the search replace to the data namespace folder.

**Comment by AJenbo** [comment]
Hmm this appears to have already been fixed, but just not tagged as a release and so not on Packagist. So I guess this is just a request of tagging 0.3.4 :)

**Comment by dusterio** [comment]
Oops, I'm gonna tag this right away :)
