### ISSUE TITLE
Why in MenaraSolutions/geographer plugin I can not get info on USA capital?

### ISSUE THREAD

**Issue by sergeynilov** [MenaraSolutions/geographer#40]
In Laravel 8 I with https://github.com/MenaraSolutions/geographer I need to get capital and its lat/lng
of any country, but I failed to get it with code:

    $selectedCountry = $earth->getCountries()->setLocale('en')->findOne(['code' => strtoupper($next_country_key)]);
    \Log::info(  varDump($selectedCountry, ' -1 $selectedCountry::') );
    $capital = $selectedCountry->getCapital();
    \Log::info(  varDump($capital, ' -1 $capital::') );
    $countriesArray[] = [
        'label' => $next_country_label,
        'value' => $next_country_key,
        'geonames_code' => $capital->getGeonamesCode(),
        'lat' => $capital->getLatitude(),
        'lng' => $capital->getLongitude(),
    ];

I got error :

    Call to a member function getGeonamesCode() on bool 

as 

    $selectedCountry->getCapital() 

returned false.

Checking in log content of $selectedCountry var I see:

    [2021-04-09 07:26:49] local.INFO:  (Object of MenaraSolutions\Geographer\Country) : -1 $selectedCountry:: : Array
    (
        [ * memberClass] => MenaraSolutions\Geographer\State
        [ * exposed] => Array
            (
                [code] => ids.iso_3166_1.0
                [code3] => ids.iso_3166_1.1
                [isoCode] => ids.iso_3166_1.0
                [numericCode] => ids.iso_3166_1.2
                [geonamesCode] => ids.geonames
                [fipsCode] => ids.fips
                [0] => area
                [1] => currency
                [phonePrefix] => phone
                [2] => mobileFormat
                [3] => landlineFormat
                [4] => trunkPrefix
                [5] => population
                [6] => continent
                [language] => languages.0
                [7] => name
            )
    
        [ * meta] => Array
            (
                [languages] => Array
                    (
                        [0] => en
                    )
    
                [ids] => Array
                    (
                        [iso_3166_1] => Array
                            (
                                [0] => US
                                [1] => USA
                                [2] => 840
                            )
    
                        [fips] => US
                        [geonames] => 6252001
                    )
    
                [long] => Array
                    (
                        [default] => United States of America
                    )
    
                [short] => Array
                    (
                        [default] => United States
                    )
    
                [area] => 9629091
                [currency] => USD
                [phone] => 1
                [trunkPrefix] => 1
                [landLineFormat] => [2-9]\d{9}
                [mobileFormat] => [2-9]\d{9}
                [continent] => NA
                [population] => 310232863
            )
    
        [ * members] => 
        [ * manager] => MenaraSolutions\Geographer\Services\DefaultManager Object
            (
                [translator:protected] => MenaraSolutions\Geographer\Services\TranslationAgency Object
                    (
                        [basePath:protected] => /mnt/_work_sdb8/wwwroot/lar/tAdsBack/vendor/menarasolutions/geographer/resources/
                        [repository:protected] => MenaraSolutions\Geographer\Repositories\File Object
                            (
                                [prefix:protected] => /mnt/_work_sdb8/wwwroot/lar/tAdsBack/vendor/menarasolutions/geographer-data/resources
                                [translationsPrefix:protected] => /mnt/_work_sdb8/wwwroot/lar/tAdsBack/vendor/menarasolutions
                                [cache:protected] => Array
                                    (
                                    )
    
                            )
    
                        [form:protected] => default
                        [inflictsTo:protected] => Array
                            (
                            )
    
                        [prepositions:protected] => 1
                        [languages:protected] => Array
                            (
                                [ru] => MenaraSolutions\Geographer\Services\Poliglottas\Russian
                                [en] => MenaraSolutions\Geographer\Services\Poliglottas\English
                                [es] => MenaraSolutions\Geographer\Services\Poliglottas\Spanish
                                [it] => MenaraSolutions\Geographer\Services\Poliglottas\Italian
                                [fr] => MenaraSolutions\Geographer\Services\Poliglottas\French
                                [zh] => MenaraSolutions\Geographer\Services\Poliglottas\Mandarin
                                [uk] => MenaraSolutions\Geographer\Services\Poliglottas\Ukrainian
                                [de] => MenaraSolutions\Geographer\Services\Poliglottas\German
                                [nl] => MenaraSolutions\Geographer\Services\Poliglottas\Dutch
                            )
    
                        [translators:protected] => Array
                            (
                            )
    
                    )
    
                [repository:protected] => MenaraSolutions\Geographer\Repositories\File Object
                    (
                        [prefix:protected] => /mnt/_work_sdb8/wwwroot/lar/tAdsBack/vendor/menarasolutions/geographer-data/resources
                        [translationsPrefix:protected] => /mnt/_work_sdb8/wwwroot/lar/tAdsBack/vendor/menarasolutions
                        [cache:protected] => Array
                            (
                            )
    
                    )
    
                [language:protected] => en
                [form:protected] => 
                [standard:protected] => iso
                [brief:protected] => 1
                [prepositions:protected] => 1
                [path:protected] => /mnt/_work_sdb8/wwwroot/lar/tAdsBack/vendor/menarasolutions/geographer/resources/
            )
    
        [ MenaraSolutions\Geographer\Divisible parent] => 
        [ * parentCode] => SOL-III
        [ * standard] => 
    )

Does this package have no info on USA capital or something wrong in my code?
I followed docs on github page...

    "menarasolutions/geographer": "^0.3.9",
    "menarasolutions/geographer-laravel": "^0.2.1",
    "laravel/framework": "^8.12",
   

 
Thanks!

**Comment by dusterio** [comment]
@sergeynilov of course it should have info about US :) I'll check what went wrong and get back to you! :)

**Comment by sergeynilov** [comment]
@dusterio, did you look into the issue? Maybe some error in my code ?  

Thanks!

**Comment by dusterio** [comment]
@sergeynilov I took a look and it turns out this part was never finished properly :) I fixed the method in the code and added a test, but somebody has to make a pull request on geographer-data repo - edit resources/cities/*.json files adding "capital" property to the corresponding entries, eg:
`
        "long": {
            "default": "Moscow"
        },
        "capital": true,
`
