### ISSUE TITLE
feature: danish translation

### ISSUE THREAD

**Issue by slaubi** [MenaraSolutions/geographer#42]
our team would like to contribute the danish translations. If you are interested, can you create the `geographer-da` repository with the english text and we create a PR with the translations?

or are there other ways on how to provide you with the needed information?

**Comment by dusterio** [comment]
@slaubi thanks, that's really appreciated! I'll create it shortly

**Comment by dusterio** [comment]
Done: https://github.com/MenaraSolutions/geographer-da
