### ISSUE TITLE
Arabic Translation Support

### ISSUE THREAD

**Issue by ZedanLab** [MenaraSolutions/geographer#45]
Our team would like to contribute to the translation into Arabic. If you are interested, can you create a "geographer-ar" repository using English translation, so that we can create a PR with Arabic translations?

**Comment by dusterio** [comment]
@ZedanLab of course, thanks for the participation!

I just created a new repository. You can take a look at the Danish package, as an example of what files/structure are required: https://github.com/MenaraSolutions/geographer-da
