### ISSUE TITLE
PHP 8.1 Errors

### ISSUE THREAD

**Issue by juanfelipepipen** [MenaraSolutions/geographer#46]
Output:

PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of MenaraSolutions\Geographer\Divisible::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by dusterio** [comment]
if we add :bool - that will break all previous versions of PHP right?

**Comment by maicol07** [comment]
@dusterio I have that error too.
If you add `:bool` it will break only PHP < 7 since return types have been introduced in PHP 7.
However, only someone is still using PHP 5.6: https://packagist.org/packages/menarasolutions/geographer/php-stats#0.3

**Comment by dusterio** [comment]
@maicol07 yep makes sense looking at the stats
I'll change this
