### ISSUE TITLE
Как получить объект города по его названию?

### ISSUE THREAD

**Issue by Alexell** [MenaraSolutions/geographer#50]
Здравствуйте.
У меня будет входной параметр - только название города на английском языке, полное. Как по нему получить объект города? Что-то не нашел такой возможности.

**Comment by dusterio** [comment]
@Alexell города с одинаковыми названиями могут быть в разных штатах/областях - название не является уникальным идентификатором

можно просто найти город по имени перебрав все города, индекса по именам городов нет
